### ISSUE TITLE
The desire to help in the project

### ISSUE THREAD

**Issue by DjaPy** [Kludex/fastapi-asyncapi#2]
Hi!

I wanted to help with the Async Api in FastApi. Interested in this expansion. Is there a road map?

I'm ready to move this for the community, but maybe I don't have enough experience.
Can I help?

**Comment by Kludex** [comment]
I've invited you as a collaborator.

If you can, contact me over Discord (Kludex#2710) or Telegram (@marcetryle), so we can discuss how to proceed. :+1:

**Comment by Kludex** [comment]
I've created this server for those who want to help: https://discord.gg/RfknXyrP
